#!/usr/bin/env node

import { readdir, readFile, writeFile } from 'fs/promises';
import { join, basename } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import fm from 'front-matter';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface BlogFrontMatter {
	title: string;
	description?: string;
	date: string;
}

interface BlogMetadata {
	title: string;
	description?: string;
	date: string; // We'll keep it as string in the generated file for Date constructor
}

async function generateBlogMetadata() {
	try {
		// Path to the blog assets directory
		const blogAssetsPath = join(__dirname, '../src/lib/assets/blog');

		// Read all files in the blog directory
		const files = await readdir(blogAssetsPath);

		// Filter for markdown files
		// Exclude files ending with .wip.md as they are work in progress
		const markdownFiles = files.filter(
			(file: string) => file.endsWith('.md') && !file.endsWith('.wip.md')
		);

		console.log(`Found ${markdownFiles.length} markdown files`);

		const blogMetadataMap: Record<string, BlogMetadata> = {};

		// Process each markdown file
		for (const file of markdownFiles) {
			const filePath = join(blogAssetsPath, file);
			const fileContent = await readFile(filePath, 'utf-8');

			try {
				// Parse front matter
				const parsed = fm<BlogFrontMatter>(fileContent);
				const { title, description, date } = parsed.attributes;

				// Validate required fields
				if (!title || !date) {
					console.warn(`Warning: Missing required front matter in ${file}. Skipping.`);
					continue;
				}

				// Use filename without extension as the key
				const key = basename(file, '.md');

				blogMetadataMap[`${key}`] = {
					title,
					description,
					date
				};

				console.log(`Processed ${file} -> ${key}`);
			} catch (error) {
				console.error(`Error parsing front matter in ${file}:`, error);
			}
		}

		// Generate the TypeScript content
		const generatedContent = generateTypeScriptContent(blogMetadataMap);

		// Write to the generated file
		const outputPath = join(__dirname, '../src/lib/blog/blogMetadata.generated.ts');
		await writeFile(outputPath, generatedContent, 'utf-8');

		console.log(
			`Successfully generated blog metadata for ${Object.keys(blogMetadataMap).length} posts`
		);
		console.log(`Output: ${outputPath}`);
	} catch (error) {
		console.error('Error generating blog metadata:', error);
		process.exit(1);
	}
}

function generateTypeScriptContent(blogMetadataMap: Record<string, BlogMetadata>): string {
	const entries = Object.entries(blogMetadataMap)
		.map(([key, metadata]) => {
			// Parse the date and format as YYYY, M, D for consistent Date constructor
			const dateObj = new Date(metadata.date);
			const year = dateObj.getFullYear();
			const month = dateObj.getMonth(); // 0-indexed
			// Use getUTCDate to avoid timezone issues from parsed object (getDate
			// gives you the local date which can be off by one day depending on tz)
			const day = dateObj.getUTCDate();

			return `\t'${key}': {
\t\ttitle: '${escapeString(metadata.title)}',
\t\tdescription: '${escapeString(metadata.description || '')}',
\t\tdate: new Date(${year}, ${month}, ${day})
\t}`;
		})
		.join(',\n');

	return `// This file is auto-generated by registerBlogs.ts
// DO NOT EDIT MANUALLY - run 'pnpm register-blogs' to regenerate

import type { BlogMetadata } from './blogMetadataType';

export const blogMetadataMap: Record<string, BlogMetadata> = {
${entries}
};
`;
}

function escapeString(str: string): string {
	return str.replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\r/g, '\\r');
}

// Run the script if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
	generateBlogMetadata();
}
