// This file is auto-generated by registerBlogs.ts
// DO NOT EDIT MANUALLY - run 'pnpm register-blogs' to regenerate

import type { BlogMetadata } from './blogMetadataType';

export const blogMetadataMap: Record<string, BlogMetadata> = {
};
